#!/bin/sh  
echo "Cleanup all old tmp files first and existing Tailscale binaries"
cd /
rm -f "/tmp/tailscaleinstall.sh"
rm -f "/tailscaleinstall.sh"
rm -f "/tmp/output.txt"
rm -f "/tmp/tailscale.tgz"
rm -f "/tailscale.tgz"
rm -f "/usr/bin/tailscale"
rm -f "/usr/bin/tailscaled"
rm -f "/etc/init.d/tailscale"
rm -f "/char-setup.sh"
rm -f "/tmp/char-setup.sh"
rm -f "/tmp/tailscalefirewall.sh"
rm -f "/tmp/1_upload.sh"
rm -f "/tmp/2_installtailscale.sh"
rm -f "/tmp/3_initscript.sh"
rm -f "/tmp/4_updatepackages.sh"
rm -f "/tmp/5_firewall.sh"
rm -f "/tmp/6_services.sh"
rm -f "/tmp/7_tailscaleup.sh"
rm -f "/tmp/8_finalcleanup.sh"
rm -rf /tmp/tailscale*/

echo "Checks key files"
FILE1="/usr/bin/tailscale"
FILE2="/usr/bin/tailscaled"
FILE3="/etc/init.d/tailscale"
FILE4="/tailscale.tgz"

echo "File check"
if [[ -f ${FILE1} ]] && [[ -f ${FILE2} ]] && [[ -f ${FILE3} ]] && [[ -f ${FILE4} ]]
then
  echo "Files still exist, exit"
  exit 1
else
  echo "Files do not exist, all ok"
  exit 0
fi
