#!/bin/sh  
echo "Configure the Tailscale init script and set permissions"
curl -L "https://raw.githubusercontent.com/earthsystems-charmaker/teltonikarouters/main/auto-install-rms/x_serviceinit" --output /etc/init.d/tailscale
chmod 775 /etc/init.d/tailscale
