#!/bin/sh
echo "Install Tailscale"
cd /
cd tmp
tar x -zvC . -f tailscale.tgz
rm -f tailscale.tgz
cd /
cd tmp
cd tailscale-*
cp tailscale /usr/bin                                                                                     
cp tailscaled /usr/bin
chmod 775 /usr/bin/tailscale
chmod 775 /usr/bin/tailscaled
cd /
cd tmp
rm tailscale-* -R
