#!/bin/sh
echo "Configuring firewall for Tailscale

echo "Appending lines to the existing /etc/config/firewall file to allow Tailscale to connect"
# First we define the block of code for the firewall config we need to set.                                                           
CONFIG_BLOCK="                                                                                                                        
config zone                                                                                                                           
    option device 'tailscale+'                                                                                                        
    option name 'tailscale'                                                                                       
    option src 'wan'                                                                                              
    option input 'ACCEPT'                                                                                         
    option forward 'REJECT'                                                                                       
    option output 'REJECT'                                                                                                            
"                                                                                                                                     
                                                                                                                  
# File path                                                                                                       
FILE_PATH="/etc/config/firewall"                                                                                  

# Writes this to the Firewall config file without a check
echo "$CONFIG_BLOCK" >> "$FILE_PATH"   
                                     
