#!/bin/sh
echo "Configuring firewall for Tailscale using the OpenWRT CLI"

uci add firewall zone
uci set firewall.@zone[-1].device='tailscale+'
uci set firewall.@zone[-1].name='tailscale'
uci set firewall.@zone[-1].src='wan'
uci set firewall.@zone[-1].input='ACCEPT'
uci set firewall.@zone[-1].forward='REJECT'
uci set firewall.@zone[-1].output='REJECT'
uci commit firewall
/etc/init.d/firewall restart
