#!/bin/sh

echo "Getting Tailscale Auth var from file"
TS_TEMP_FILE="/tmp/ts_temp_file"
TAILSCALE_AUTH_KEY_EXECUTE=$(cat "$TS_TEMP_FILE")

echo "Running Tailscale UP"
LOCAL_IPv4=$(route -n | awk '$8 == "br-lan" && $1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $1}')
THIRD_OCTET=$(echo "$LOCAL_IPv4" | cut -d '.' -f 3)
tailscale up --authkey ${TAILSCALE_AUTH_KEY_EXECUTE} --advertise-routes="172.20.${THIRD_OCTET}.0/24" --accept-dns=false --advertise-tags="tag:char-routers"

echo "Cleaning up Tailscale Auth tmp file"
rm -f "/tmp/ts_temp_file"

echo "Clearing variables"
unset TAILSCALE_AUTH_KEY_EXECUTE
unset TS_TEMP_FILE

echo "Check Tailscale is UP"
STATUS_IP="$(tailscale ip -4 | awk -F'.' '(print $1)')"
if [ "${STATUS_IP}" = "100" ]; 
then
    echo "Tailscale has an 100.x.x.x. IP address, its authenticated and running, all ok"
    exit 0
else 
    echo "Tailscale has no IP, exit 1"  
    exit 1  
fi
