#!/bin/sh

echo "Getting Tailscale Auth var from file"
TS_TEMP_FILE="/tmp/ts_temp.txt"
TAILSCALE_AUTH_KEY_EXECUTE=$(cat "$TS_TEMP_FILE")

echo "Running Tailscale UP"
LOCAL_IPv4=$(route -n | awk '$8 == "br-lan" && $1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $1}')
THIRD_OCTET=$(echo "$LOCAL_IPv4" | cut -d '.' -f 3)
tailscale up --authkey ${TAILSCALE_AUTH_KEY_EXECUTE} --advertise-routes="172.20.${THIRD_OCTET}.0/24" --accept-dns=false --advertise-tags="tag:char-routers"

echo "Cleaning up Tailscale Auth tmp file"
rm -f "/tmp/ts_temp.txt"

echo "Removing variables"
unset TAILSCALE_AUTH_KEY_EXECUTE
unset TS_TEMP_FILE
