#!/bin/sh  
echo "Cleanup all old tmp files from the install "
cd /
rm -f "/tmp/tailscale.tgz"
rm -f "/tmp/0_upload.sh"
rm -f "/tmp/1_cleanup.sh"
rm -f "/tmp/2_installtailscale.sh"
rm -f "/tmp/3_initscript.sh"
rm -f "/tmp/4_updatepackages.sh"
rm -f "/tmp/5_firewall.sh"
rm -f "/tmp/6_services.sh"
rm -f "/tmp/7_tailscaleup.sh"
rm -f "/tmp/7_tailscaleup_noauth.sh"
rm -f "/tmp/ts_temp_file"
rm -rf /tmp/tailscale*/
rm -f "/tmp/8_finalcleanup.sh"
